---
- name: notify discord
  hosts: "{{ hosts }}"
  tasks:
    - name: send discord message
      uri:
        url: "https://discord.com/api/webhooks/1186749805465186437/3TT5WTr5otcmR8LBo24zW-bPvw-KGyZ_ZSElJMVtFwu2aid48WZ_Rwba-bxhwCyeM87L"
        method: POST
        body_format: json
        body: '{"content": "your-message"}'
        headers:
          Content-Type: application/json
        status_code: 204
      # when: your-condition
